services:
  cwa-bd:
    container_name: cwa-bd
    image: ghcr.io/calibrain/shelfmark:v1.1.0
    environment:
      UID: ${UID}
      GID: ${GID}
      FLASK_PORT: 8084
      FLASK_DEBUG: false
      USE_BOOK_TITLE: true
      BOOK_LANGUAGE: nl
      USE_CF_BYPASS: true
    restart: unless-stopped
    volumes:
      - ${MEDIA_DIR}/downloads/usenet/books:/cwa-book-ingest
    networks:
      - npm
    labels:
      - traefik.enable=true
      - traefik.http.routers.cwa-bd.rule=Host(`cwa-bd.${DOMAIN}`)
      - traefik.http.routers.cwa-bd.entrypoints=websecure
      - traefik.http.routers.cwa-bd.tls=true
      - traefik.http.services.cwa-bd.loadbalancer.server.port=8084
networks:
  npm:
    external: true
