services:
  duplicacy:
    container_name: duplicacy
    hostname: duplicacy
    image: ghcr.io/hotio/duplicacy:release-1.8.0@sha256:6cb785597c46b2df7dae58c851e372887b4418ec6eb41624a6a1a64d4d267d46
    #    ports:
    #      - "3875:3875"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=002
      - TZ=Europe/Amsterdam
    volumes:
      - ${DOCKER_DATA_DIR}/duplicacy/config:/config
      - ${DOCKER_DATA_DIR}/duplicacy/cache:/cache
      - ${DOCKER_DATA_DIR}/duplicacy/logs:/logs
      - ${DOCKER_DATA_DIR}/duplicacy/creds:/creds
      - ${MEDIA_DIR}/nextcloud:/data:ro
      - ${DOCKER_STACKS_DIR}:/opt/stacks:ro
      - ${DOCKER_DATA_DIR}/:/mnt/data:ro
    labels:
      - homepage.group=Infra
      - homepage.name=Duplicacy
      - homepage.icon=duplicacy.png
      - homepage.href=http://duplicacy.${DOMAIN}/
      - homepage.description=A new generation cloud backup tool
      - traefik.enable=true
      - traefik.http.routers.duplicacy.rule=Host(`duplicacy.${DOMAIN}`)
      - traefik.http.routers.duplicacy.entrypoints=websecure
      - traefik.http.routers.duplicacy.tls=true
      - traefik.http.services.duplicacy.loadbalancer.server.port=3875
    restart: unless-stopped
    networks:
      - npm
networks:
  npm:
    external: true