services:
  tautulli:
    image: ghcr.io/tautulli/tautulli:v2.16.1@sha256:5f3603345e3334bd30aadf9e1fa9b0acb401b5225cc42e9b7a3dbf660532fbd9
    container_name: tautulli
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Europe/Amsterdam
    volumes:
      - ${DOCKER_DATA_DIR}/tautulli/config:/config
      - ${DOCKER_DATA_DIR}/tautulli/scripts:/scripts
    #    ports:
    #      - 8181:8181
    labels:
      - homepage.group=Media
      - homepage.name=Tautulli
      - homepage.icon=tautulli.png
      - homepage.href=http://tautulli.${DOMAIN}/
      - homepage.description=Monitoring and tracking tool for Plex Media Server
      - homepage.widget.type=tautulli
      - homepage.widget.url=http://tautulli:8181
      - homepage.widget.key=${TAUTULLI_API}
      - traefik.enable=true
      - traefik.http.routers.tautulli.rule=Host(`tautulli.${DOMAIN}`)
      - traefik.http.routers.tautulli.entrypoints=websecure
      - traefik.http.routers.tautulli.tls=true
      - traefik.http.services.tautulli.loadbalancer.server.port=8181
    restart: unless-stopped
networks:
  default:
    external: true
    name: npm
