services:
  code-server:
    image: linuxserver/code-server:4.106.3@sha256:aab9520fe923b2d93dccc2c806f3dc60649c2f4a2847fcd40c942227d0f1ae8f
    container_name: code-server
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Europe/Amsterdam
      - PROXY_DOMAIN=codeserver.${DOMAIN}
      - DEFAULT_WORKSPACE=/stacks
    volumes:
      - ${DOCKER_DATA_DIR}/code-server/config:/config
      - ${DOCKER_DATA_DIR}/homepage/config:/homepage
      - ${DOCKER_STACKS_DIR}:/stacks
    labels:
      - homepage.group=Infra
      - homepage.name=Codeserver
      - homepage.icon=vscode.png
      - homepage.href=http://codeserver.${DOMAIN}/
      - homepage.description=VS Code in the browser
      - traefik.enable=true
      - traefik.http.routers.code-server.rule=Host(`codeserver.${DOMAIN}`)
      - traefik.http.routers.code-server.entrypoints=websecure
      - traefik.http.routers.code-server.tls=true
      - traefik.http.services.code-server.loadbalancer.server.port=8443
    restart: unless-stopped
    networks:
      - npm
networks:
  npm:
    external: true