services:
  overseerr:
    image: sctx/overseerr:1.35.0@sha256:6197516c9d7b58ccf113455e32aafb94df5d91995fe50e8c2cae6ba6c7c7b7de
    container_name: overseerr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Europe/Amsterdam
    volumes:
      - ${DOCKER_DATA_DIR}/overseerr/config:/app/config
      - ${DOCKER_DATA_DIR}/overseerr/images/logo_full.png:/app/overseerr/public/logo_full.png
      - ${DOCKER_DATA_DIR}/overseerr/images/logo_full.svg:/app/overseerr/public/logo_full.svg
      - ${DOCKER_DATA_DIR}/overseerr/images/logo_stacked.svg:/app/overseerr/public/logo_stacked.svg
    labels:
      - traefik.enable=true
      - traefik.http.routers.overseerr.rule=Host(`overseerr.${DOMAIN}`)
      - traefik.http.routers.overseerr.entrypoints=websecure
      - traefik.http.routers.overseerr.tls=true
      - traefik.http.services.overseerr.loadbalancer.server.port=5055
      - homepage.group=Media
      - homepage.name=Overseerr
      - homepage.icon=overseerr.png
      - homepage.href=http://overseerr.${DOMAIN}/
      - homepage.description=Media request management
      - homepage.widget.fields=["pending", "processing"]
      - homepage.widget.type=overseerr
      - homepage.widget.url=http://overseerr:5055
      - homepage.widget.key=${OVERSEERR_API}
    restart: unless-stopped
    networks:
      - npm
  overseerr_private:
    image: ghcr.io/seerr-team/seerr:develop@sha256:395542ebb42be004b57a1fd658369fa1f8f9937727c9edd55b0feee0ccbc7943
    init: true
    container_name: overseerr_private
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Europe/Amsterdam
    volumes:
      - ${DOCKER_DATA_DIR}/overseerrprivate/config:/app/config
    labels:
      - traefik.enable=true
      - traefik.http.routers.overseerr-private.rule=Host(`overseerrprivate.${DOMAIN}`)
      - traefik.http.routers.overseerr-private.entrypoints=websecure
      - traefik.http.routers.overseerr-private.tls=true
      - traefik.http.services.overseerr-private.loadbalancer.server.port=5055
      - homepage.group=Media
      - homepage.name=Overseerr Private
      - homepage.icon=overseerr.png
      - homepage.href=http://overseerrprivate.${DOMAIN}/
      - homepage.description=Media request management
      - homepage.widget.fields=["pending", "processing"]
      - homepage.widget.type=overseerr
      - homepage.widget.url=http://overseerr_private:5055
      - homepage.widget.key=${OVERSEERRPRIVATE_API}
    restart: unless-stopped
    networks:
      - npm
networks:
  npm:
    external: true