services:
  dockerproxy:
    image: linuxserver/socket-proxy:3.2.10@sha256:687b9ff41af197d9eb3d565d014973df6406dab15333a51de564210d6d8082f6
    container_name: dockerproxy
    environment:
      - CONTAINERS=1 # Allow access to viewing containers
      - SERVICES=1 # Allow access to viewing services (necessary when using Docker Swarm)
      - TASKS=1 # Allow access to viewing tasks (necessary when using Docker Swarm)
      - POST=0 # Disallow any POST operations (effectively read-only)
      - IMAGES=1
    #    ports:
    #      - 127.0.0.1:2375:2375
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro # Mounted as read-only
    restart: unless-stopped
    networks:
      - npm
    read_only: true
    tmpfs:
      - /run
networks:
  npm:
    external: true