services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:2.32.0@sha256:de4daea50968fe2bb0b6c543c5586601cee14f2ea7543544c89ebea94491005c
    container_name: audiobookshelf
    #    ports:
    #      - 13378:80
    volumes:
      - ${MEDIA_DIR}/music/Audiobooks/:/audiobooks
      - ${MEDIA_DIR}/music/podcasts/:/podcasts
      - ${DOCKER_DATA_DIR}/audiobookshelf/config:/config
      - ${DOCKER_DATA_DIR}/audiobookshelf/metadata:/metadata
    environment:
      - TZ=Europe/Amsterdam
      - PUID=${PUID}
      - PGID=${PGID}
    networks:
      - npm
    labels:
      - homepage.group=Media
      - homepage.name=Audiobookshelf
      - homepage.icon=audiobookshelf.png
      - homepage.href=http://audiobookshelf.${DOMAIN}/
      - homepage.description=Audiobook and podcast server
      - homepage.widget.type=audiobookshelf
      - homepage.widget.fields=["podcasts", "books"]
      - homepage.widget.url=http://audiobookshelf:80
      - homepage.widget.key=${AUDIOBOOKSELF_API}
      - traefik.enable=true
      - traefik.docker.network=npm
      - traefik.http.routers.audiobookshelf.rule=Host(`audiobookshelf.${DOMAIN}`)
      - traefik.http.routers.audiobookshelf.entrypoints=websecure
      - traefik.http.routers.audiobookshelf.tls=true
      - traefik.http.services.audiobookshelf.loadbalancer.server.port=80
    restart: unless-stopped
networks:
  npm:
    external: true