services:
  plex:
    image: linuxserver/plex:1.43.0@sha256:55c2def2eb662c2ce1a13e569278aeb87b2509ac7c57711d0da0a5d6d1607ad8
    container_name: plex
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Europe/Amsterdam
      - VERSION=docker
    devices:
      - /dev/dri/:/dev/dri/
    networks:
      my-macvlan-net:
        ipv4_address: ${PLEX_IP}
      npm: null
    volumes:
      - ${DOCKER_DATA_DIR}/plex/config:/config
      - ${DOCKER_DATA_DIR}/plex/transcode:/transcode
      - ${MEDIA_DIR}:/media
      - ${DOCKER_DATA_DIR}/plex/preroll:/preroll
    labels:
      - homepage.group=Media
      - homepage.name=Plex
      - homepage.icon=plex.png
      - homepage.href=https://plex.${DOMAIN}/
      - homepage.description=mediaserver
      - homepage.widget.type=plex
      - homepage.widget.fields=["movies", "tv"]
      - homepage.widget.url=http://plex:32400
      - homepage.widget.key=${PLEX_TOKEN}
      - traefik.enable=true
      - traefik.docker.network=npm
      - traefik.http.routers.plex.rule=Host(`plex.${DOMAIN}`)
      - traefik.http.routers.plex.entrypoints=websecure
      - traefik.http.routers.plex.tls=true
      - traefik.http.services.plex.loadbalancer.server.port=32400
    restart: unless-stopped
networks:
  npm:
    external: true
  my-macvlan-net:
    external: true
