services:
  triliumnext:
    image: triliumnext/trilium:v0.100.0@sha256:8a8f15720c50583e82bc180ca1820942f1a2ffb4ce70ab65eab1bf051b55e440
    restart: unless-stopped
    environment:
      - TRILIUM_DATA_DIR=/home/node/trilium-data
    #    ports:
    #      - "8080:8080"
    volumes:
      - ${DOCKER_DATA_DIR}/triliumnext/config:/home/node/trilium-data
    networks:
      - npm
networks:
  npm:
    external: true