services:
  triliumnext:
    image: triliumnext/trilium:v0.101.3@sha256:f9c978d08f24af19e58c7e3230218a5a6a0ab889ac261e25edb847ebd3762ff4
    restart: unless-stopped
    environment:
      - TRILIUM_DATA_DIR=/home/node/trilium-data
    #    ports:
    #      - "8080:8080"
    volumes:
      - ${DOCKER_DATA_DIR}/triliumnext/config:/home/node/trilium-data
    networks:
      - npm
networks:
  npm:
    external: true