services:
  bentopdf:
    image: bentopdf/bentopdf-simple:v1.7.1@sha256:eefb372e9986b32364256a11b1dc31604b1b1e2b407134078ccf246cc9a671e0
    container_name: bentopdf
    restart: unless-stopped
#    ports:
#      - '3000:80'
    networks:
      - npm
    labels:
      - homepage.group=Media
      - homepage.name=BentoPDF
      - homepage.icon=sh-bentopdf-dark.png
      - homepage.href=http://pdf.${DOMAIN}/
      - homepage.description=A powerful, privacy-first, client-side PDF toolkit
      - traefik.enable=true
      - traefik.docker.network=npm
      - traefik.http.routers.bentopdf.rule=Host(`pdf.${DOMAIN}`)
      - traefik.http.routers.bentopdf.entrypoints=websecure
      - traefik.http.routers.bentopdf.tls=true
      - traefik.http.services.bentopdf.loadbalancer.server.port=8080
networks:
  npm:
    external: true