services:
  bentopdf:
    image: bentopdf/bentopdf-simple:v1.10.4@sha256:1bb96efc9300120e368901882db21e0c7d8327e4ce7529e3d51bb079b4ffcdca
    container_name: bentopdf
    restart: unless-stopped
#    ports:
#      - '3000:80'
    networks:
      - npm
    labels:
      - homepage.group=Media
      - homepage.name=BentoPDF
      - homepage.icon=sh-bentopdf-dark.png
      - homepage.href=http://pdf.${DOMAIN}/
      - homepage.description=A powerful, privacy-first, client-side PDF toolkit
      - traefik.enable=true
      - traefik.docker.network=npm
      - traefik.http.routers.bentopdf.rule=Host(`pdf.${DOMAIN}`)
      - traefik.http.routers.bentopdf.entrypoints=websecure
      - traefik.http.routers.bentopdf.tls=true
      - traefik.http.services.bentopdf.loadbalancer.server.port=8080
networks:
  npm:
    external: true