services:
  orcaslicer:
    image: linuxserver/orcaslicer:2.3.1@sha256:dc8b229d48bad7e4a89633174632b71c9dde41017912c7264491f0520b5f24fa
    container_name: orcaslicer
    devices:
      - /dev/dri/:/dev/dri/
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Europe/Amsterdam
    volumes:
      - ${DOCKER_DATA_DIR}/orcaslicer/config:/config
    networks:
      - npm
    shm_size: "1gb"
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.orcaslicer.rule=Host(`orcaslicer.${DOMAIN}`)
      - traefik.http.routers.orcaslicer.entrypoints=websecure
      - traefik.http.routers.orcaslicer.tls=true
      - traefik.http.services.orcaslicer.loadbalancer.server.port=3000
networks:
  npm:
    external: true