services:
  orcaslicer:
    image: linuxserver/orcaslicer:2.3.1@sha256:4bded411f6fb4c69a84aba038e025956765d1e3e9d568865dbeea926fa2fa050
    container_name: orcaslicer
    devices:
      - /dev/dri/:/dev/dri/
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Europe/Amsterdam
    volumes:
      - ${DOCKER_DATA_DIR}/orcaslicer/config:/config
    networks:
      - npm
    shm_size: "1gb"
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.orcaslicer.rule=Host(`orcaslicer.${DOMAIN}`)
      - traefik.http.routers.orcaslicer.entrypoints=websecure
      - traefik.http.routers.orcaslicer.tls=true
      - traefik.http.services.orcaslicer.loadbalancer.server.port=3000
networks:
  npm:
    external: true