services:
  orcaslicer:
    image: linuxserver/orcaslicer:2.3.1
    container_name: orcaslicer
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Europe/Amsterdam
    volumes:
      - ${DOCKER_DATA_DIR}/orcaslicer/config:/config
    shm_size: "1gb"
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.orcaslicer.rule=Host(`orcaslicer.${DOMAIN}`)
      - traefik.http.routers.orcaslicer.entrypoints=websecure
      - traefik.http.routers.orcaslicer.tls=true
      - traefik.http.services.orcaslicer.loadbalancer.server.port=3000
networks:
  npm:
    external: true