services:
  homepage:
    image: ghcr.io/gethomepage/homepage:v1.10.1@sha256:0b596092c0b55fe4c65379a428a3fe90bd192f10d1b07d189a34fe5fabe7eedb
    container_name: homepage
    volumes:
      - ${DOCKER_DATA_DIR}/homepage/config:/app/config
    networks:
      - npm
    restart: unless-stopped
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - HOMEPAGE_ALLOWED_HOSTS=${DOMAIN}
    labels:
      - traefik.enable=true
      - traefik.http.routers.homepage.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.homepage.entrypoints=websecure
      - traefik.http.routers.homepage.tls=true
      - traefik.http.services.homepage.loadbalancer.server.port=3000
networks:
  npm:
    external: true
