services:
  homepage:
    image: ghcr.io/gethomepage/homepage:v1.10.0@sha256:435e642bf3aac95352218ca18f07b05d1f43a7b666efdbaf6a3bc97f16da6b3e
    container_name: homepage
    volumes:
      - ${DOCKER_DATA_DIR}/homepage/config:/app/config
    networks:
      - npm
    restart: unless-stopped
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - HOMEPAGE_ALLOWED_HOSTS=${DOMAIN}
    labels:
      - traefik.enable=true
      - traefik.http.routers.homepage.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.homepage.entrypoints=websecure
      - traefik.http.routers.homepage.tls=true
      - traefik.http.services.homepage.loadbalancer.server.port=3000
networks:
  npm:
    external: true
