services:
  homepage:
    image: ghcr.io/gethomepage/homepage:v1.6.0@sha256:4ab33a0b91f382c07c6734c6102b16594e8d386347f0704460172fcd16f11443
    container_name: homepage
    volumes:
      - ${DOCKER_DATA_DIR}/homepage/config:/app/config
    networks:
      - npm
    restart: unless-stopped
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - HOMEPAGE_ALLOWED_HOSTS=${DOMAIN}
    labels:
      - traefik.enable=true
      - traefik.http.routers.homepage.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.homepage.entrypoints=websecure
      - traefik.http.routers.homepage.tls=true
      - traefik.http.services.homepage.loadbalancer.server.port=3000
networks:
  npm:
    external: true
