services:
  headless-chrome:
    #ports:
    #   - 9222:9222
    container_name: headless-chrome
    image: chromedp/headless-shell:145.0.7632.5@sha256:1d623a0c6027b7ab5fef3e54b4ae5fab453fb7d005c41b16e01c73d6b3813423
    restart: unless-stopped
    networks:
      - npm
networks:
  npm:
    external: true
