services:
  headless-chrome:
    #ports:
    #   - 9222:9222
    container_name: headless-chrome
    image: chromedp/headless-shell:146.0.7647.4@sha256:487ab195e27de246731fa68b9621ff4ee96bef99da98f93b5ebda1ad4955c401
    restart: unless-stopped
    networks:
      - npm
networks:
  npm:
    external: true
