services:
  headless-chrome:
    #ports:
    #   - 9222:9222
    container_name: headless-chrome
    image: chromedp/headless-shell:145.0.7572.3@sha256:02391efd25fb93295df57814124edea4c8687955c02e1ee35eb64d48094f4981
    restart: unless-stopped
    networks:
      - npm
networks:
  npm:
    external: true
