services:
  headless-chrome:
    #ports:
    #   - 9222:9222
    container_name: headless-chrome
    image: chromedp/headless-shell:146.0.7655.3@sha256:b32662b4dde4e7923bb64a7be4d5f3e3d4bf7174682926fc36c28fbb93596258
    restart: unless-stopped
    networks:
      - npm
networks:
  npm:
    external: true
