services:
  headless-chrome:
    #ports:
    #   - 9222:9222
    container_name: headless-chrome
    image: chromedp/headless-shell:147.0.7695.0@sha256:dfd1e06c5003397b05f4ab53c48e51caa75671cac6c54a4f9556d6ed691e99b7
    restart: unless-stopped
    command:
      - --remote-allow-origins=*
    networks:
      npm:
        ipv4_address: 172.16.2.5
networks:
  npm:
    external: true