services:
  headless-chrome:
    #ports:
    #   - 9222:9222
    container_name: headless-chrome
    image: chromedp/headless-shell:146.0.7635.3@sha256:f0248a82e3e87c7829bd79de1aeb9be786616db1ba42206c0bdfc349e9e6f86a
    restart: unless-stopped
    networks:
      - npm
networks:
  npm:
    external: true
