services:
  headless-chrome:
    #ports:
    #   - 9222:9222
    container_name: headless-chrome
    image: chromedp/headless-shell:146.0.7680.0@sha256:de210061225d8398c3ec96e6d32a924efb7913629a207fe6dfa70d5538089cf6
    restart: unless-stopped
    command:
      - --remote-allow-origins=*
    networks:
      npm:
        ipv4_address: 172.16.2.5
networks:
  npm:
    external: true