services:
  headless-chrome:
    #ports:
    #   - 9222:9222
    container_name: headless-chrome
    image: chromedp/headless-shell:146.0.7680.16@sha256:79ce9e1e2c3186aa888b5441968069cd516a657cad62d6e44e4905481e292e4a
    restart: unless-stopped
    command:
      - --remote-allow-origins=*
    networks:
      npm:
        ipv4_address: 172.16.2.5
networks:
  npm:
    external: true