services:
  headless-chrome:
    #ports:
    #   - 9222:9222
    container_name: headless-chrome
    image: chromedp/headless-shell:145.0.7620.3@sha256:192b9653a7b84458b1acd5646dcfa5612a33d08fb19833d0f93fcabb41333492
    restart: unless-stopped
    networks:
      - npm
networks:
  npm:
    external: true
