services:
  diun:
    image: crazymax/diun:4.31.0@sha256:3e277cd1f1262fe6ff1047e5550f6f2e1c860c3c60b0058625e3c69888a4cc8d
    container_name: diun
    command: serve
    volumes:
      - ${DOCKER_DATA_DIR}/diun/config:/data
    environment:
      - TZ=Europe/Amsterdam
      - DIUN_PROVIDERS_DOCKER_ENDPOINT=tcp://dockerproxy:2375
      - LOG_LEVEL=info
      - LOG_JSON=false
      - DIUN_WATCH_WORKERS=20
      - DIUN_WATCH_SCHEDULE=0 */6 * * *
      - DIUN_WATCH_JITTER=30s
      - DIUN_PROVIDERS_DOCKER=true
      - DIUN_PROVIDERS_DOCKER_WATCHBYDEFAULT=false
      - DIUN_NOTIF_GOTIFY_ENDPOINT=${ENDPOINT}
      - DIUN_NOTIF_GOTIFY_TOKEN=${TOKEN}
    restart: unless-stopped
    networks:
      - npm
networks:
  npm:
    external: true