services:
  papra:
    image: ghcr.io/papra-hq/papra:latest@sha256:c0608d9d2be9914f0eec1947236faf3167219a788ac225c083195abcd91eeca4
    container_name: papra
    restart: unless-stopped
#    ports:
#      - 1221:1221
    environment:
      - AUTH_SECRET=${AUTH_SECRET}
      - APP_BASE_URL=https://papra.${DOMAIN}
    volumes:
      - ${DOCKER_DATA_DIR}/papra/config:/app/app-data
    user: ${PUID}:${PGID}
    networks:
      - npm
networks:
  npm:
    external: true