services:
  papra:
    image: ghcr.io/papra-hq/papra:latest@sha256:e41d2237a59b072063e4059a85492cb11fe4aefb706851becbbce88c7c2ae072
    container_name: papra
    restart: unless-stopped
#    ports:
#      - 1221:1221
    environment:
      - AUTH_SECRET=${AUTH_SECRET}
      - APP_BASE_URL=https://papra.${DOMAIN}
    volumes:
      - ${DOCKER_DATA_DIR}/papra/config:/app/app-data
    user: ${PUID}:${PGID}
    networks:
      - npm
networks:
  npm:
    external: true