services:
  quickstart:
    image: kometateam/quickstart:v0.9.5@sha256:958e5a049adb8db7e508fac20d1d91a5d4fd918f4db6bee6d2a9a2fe3857170f
    container_name: quickstart
#    ports:
#      - 7171:7171
    environment:
      - TZ=Europe/Amsterdam
    volumes:
      - ${DOCKER_DATA_DIR}/quickstart/config:/config
    restart: unless-stopped
    networks:
      - npm
networks:
  npm:
    external: true