services:
  quickstart:
    image: kometateam/quickstart:v0.9.11@sha256:819d7255e143fcd00bd149474d8bf00cff9684cadf26761f832fe990abcdff6c
    container_name: quickstart
#    ports:
#      - 7171:7171
    environment:
      - TZ=Europe/Amsterdam
    volumes:
      - ${DOCKER_DATA_DIR}/quickstart/config:/config
    restart: unless-stopped
    networks:
      - npm
networks:
  npm:
    external: true