services:
  quickstart:
    image: kometateam/quickstart:v0.9.10@sha256:58a4b30d1123fd7a4193b42f5825547c361da09342dbc10828992eda0c714f94
    container_name: quickstart
#    ports:
#      - 7171:7171
    environment:
      - TZ=Europe/Amsterdam
    volumes:
      - ${DOCKER_DATA_DIR}/quickstart/config:/config
    restart: unless-stopped
    networks:
      - npm
networks:
  npm:
    external: true