services:
  retrom:
    container_name: retrom
    image: ghcr.io/jmberesford/retrom-service:v0.7.52@sha256:226a7d6b9786cb7e48fa9971be6bb3e3b69366c433a1338d77bc72d9627e8efc
#    ports:
#      - 5101:5101
    volumes:
      - ${MEDIA_DIR}/retro/roms:/app/library:ro
      - ${DOCKER_DATA_DIR}/retrom/config:/app/config
      - ${DOCKER_DATA_DIR}/retrom/data:/app/data/
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    restart: unless-stopped
    networks:
      - npm
networks:
  npm:
    external: true