services:
  retrom:
    container_name: retrom
    image: ghcr.io/jmberesford/retrom-service:v0.7.49@sha256:a7e0fc67703333dee631a4ddef2cd3f36ecd14cf414b99229a1e089501bcd006
#    ports:
#      - 5101:5101
    volumes:
      - ${MEDIA_DIR}/retro/roms:/app/library:ro
      - ${DOCKER_DATA_DIR}/retrom/config:/app/config
      - ${DOCKER_DATA_DIR}/retrom/data:/app/data/
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    restart: unless-stopped
    networks:
      - npm
networks:
  npm:
    external: true