services:
  profilarr:
    image: santiagosayshey/profilarr:beta
    container_name: profilarr
    volumes:
      - ${DOCKER_DATA_DIR}/profilarr/config:/config # Replace with your actual path
    environment:
      - TZ=Europe/Amsterdam # Set your timezone
    restart: unless-stopped
    networks:
      - npm
    labels:
      - homepage.group=Media Management
      - homepage.name=Profilarr
      - homepage.id=colsmall
      - homepage.icon=https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/72x72/1f4d2.png
      - homepage.href=http://profilarr.${DOMAIN}/
      - homepage.description=Config management for -arr suite
      - traefik.enable=true
      - traefik.http.routers.profilarr.rule=Host(`profilarr.${DOMAIN}`)
      - traefik.http.routers.profilarr.entrypoints=websecure
      - traefik.http.routers.profilarr.tls=true
      - traefik.http.services.profilarr.loadbalancer.server.port=6868
networks:
  npm:
    external: true