services:
  firefox:
    image: linuxserver/firefox:1147.0.4@sha256:d13270084850ad869a683675e0b376d1361d982c98d260c51ff6916c374a858e
    container_name: firefox
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Europe/Amsterdam
      - FIREFOX_CLI=https://www.startpage.com/ #optional
    volumes:
      - ${DOCKER_DATA_DIR}/firefox/config:/config
    #   ports:
    #     - 3000:3000
    #     - 3001:3001
    shm_size: 1gb
    restart: unless-stopped
    networks:
      - npm
networks:
  npm:
    external: true
