services:
  bazarr:
    image: linuxserver/bazarr:1.5.3@sha256:2be164c02c0bb311b6c32e57d3d0ddc2813d524e89ab51a3408c1bf6fafecda5
    container_name: bazarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Europe/Amsterdam
    volumes:
      - ${DOCKER_DATA_DIR}/bazarr/config:/config
      - ${MEDIA_DIR}:/media
    labels:
      - homepage.group=Media Management
      - homepage.name=Bazarr
      - homepage.id=colsmall
      - homepage.icon=bazarr.png
      - homepage.href=http://bazarr.${DOMAIN}/
      - homepage.description=Subtitle management
      - homepage.widget.type=bazarr
      - homepage.widget.url=http://bazarr:6767
      - homepage.widget.key=${BAZARR_API}
      - traefik.enable=true
      - traefik.docker.network=npm
      - traefik.http.routers.bazarr-api.rule=Host(`bazarr.${DOMAIN}`) && PathPrefix(`/api`)
      - traefik.http.routers.bazarr-api.entrypoints=websecure
      - traefik.http.routers.bazarr-api.priority=100
      - traefik.http.routers.bazarr-api.tls=true
      - traefik.http.routers.bazarr-api.service=bazarr
      - traefik.http.routers.bazarr.rule=Host(`bazarr.${DOMAIN}`)
      - traefik.http.routers.bazarr.entrypoints=websecure
      - traefik.http.routers.bazarr.priority=99
      - traefik.http.routers.bazarr.tls=true
      - traefik.http.routers.bazarr.middlewares=authentik-forwardauth@docker
      - traefik.http.routers.bazarr.service=bazarr
      - traefik.http.services.bazarr.loadbalancer.server.port=6767
    restart: unless-stopped
    networks:
      - npm
  bazarrexternal:
    image: linuxserver/bazarr:1.5.3@sha256:2be164c02c0bb311b6c32e57d3d0ddc2813d524e89ab51a3408c1bf6fafecda5
    container_name: bazarrexternal
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Europe/Amsterdam
    volumes:
      - ${DOCKER_DATA_DIR}/bazarrexternal/config:/config
      - ${MEDIA_DIR}:/media
    labels:
      - homepage.group=Media Management
      - homepage.name=Bazarr external
      - homepage.id=colsmall
      - homepage.icon=bazarr.png
      - homepage.href=http://bazarrexternal.${DOMAIN}/
      - homepage.description=Subtitle management
      - homepage.widget.type=bazarr
      - homepage.widget.url=http://bazarrexternal:6767
      - homepage.widget.key=${BAZARREXTERNAL_API}
      - traefik.enable=true
      - traefik.docker.network=npm
      - traefik.http.routers.bazarrexternal-api.rule=Host(`bazarrexternal.${DOMAIN}`) && PathPrefix(`/api`)
      - traefik.http.routers.bazarrexternal-api.entrypoints=websecure
      - traefik.http.routers.bazarrexternal-api.priority=100
      - traefik.http.routers.bazarrexternal-api.tls=true
      - traefik.http.routers.bazarrexternal-api.service=bazarrexternal
      - traefik.http.routers.bazarrexternal.rule=Host(`bazarrexternal.${DOMAIN}`)
      - traefik.http.routers.bazarrexternal.entrypoints=websecure
      - traefik.http.routers.bazarrexternal.priority=99
      - traefik.http.routers.bazarrexternal.tls=true
      - traefik.http.routers.bazarrexternal.middlewares=authentik-forwardauth@docker
      - traefik.http.routers.bazarrexternal.service=bazarrexternal
      - traefik.http.services.bazarrexternal.loadbalancer.server.port=6767
    restart: unless-stopped
    networks:
      - npm
networks:
  npm:
    external: true