services:
  ollama:
    image: ollama/ollama:0.17.2@sha256:917c942fbd5b3d659f830d08b48da466ce9bb1e56e2fc3d920d8e835a0922318
    container_name: ollama
    restart: unless-stopped
    environment:
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_KEEP_ALIVE=24h
    volumes:
      - ${DOCKER_DATA_DIR}/ollama:/root/.ollama
    networks:
      - npm

    # --- OPTIONAL: NVIDIA GPU ---
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           capabilities: [gpu]
    #           count: 1

networks:
  npm:
    external: true