services:
  ollama:
    image: ollama/ollama:0.15.3@sha256:3970c9b21fc1286d2958dd33f9a4774d70a9b63d596c61ad0ed5b5dd28291dbe
    container_name: ollama
    restart: unless-stopped
    environment:
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_KEEP_ALIVE=24h
    volumes:
      - ${DOCKER_DATA_DIR}/ollama:/root/.ollama
    networks:
      - npm

    # --- OPTIONAL: NVIDIA GPU ---
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           capabilities: [gpu]
    #           count: 1

networks:
  npm:
    external: true