services:
  ollama:
    image: ollama/ollama:0.13.4@sha256:78b19735971f9a2855c98ca39a775a43fd3ebe104af0fe2155b5261c34deef31
    container_name: ollama
    restart: unless-stopped
    environment:
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_KEEP_ALIVE=24h
    volumes:
      - ${DOCKER_DATA_DIR}/ollama:/root/.ollama
    networks:
      - npm

    # --- OPTIONAL: NVIDIA GPU ---
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           capabilities: [gpu]
    #           count: 1

networks:
  npm:
    external: true