services:
  uptime-kuma:
    restart: unless-stopped
    #    ports:
    #      - 3001:3001
    environment:
      - TZ=Europe/Amsterdam
    volumes:
      - ${DOCKER_DATA_DIR}/uptime-kuma/config:/app/data
    container_name: uptime-kuma
    image: louislam/uptime-kuma:2.0.2@sha256:4c364ef96aaddac7ec4c85f5e5f31c3394d35f631381ccbbf93f18fd26ac7cba
    networks:
      - npm
    labels:
      - homepage.group=Infra
      - homepage.name=Uptime Kuma
      - homepage.icon=uptime-kuma.png
      - homepage.href=http://uptime.${DOMAIN}/
      - homepage.description=A fancy self-hosted monitoring tool
      - homepage.widget.type=uptimekuma
      - homepage.widget.url=http://uptime-kuma:3001
      - homepage.widget.slug=uptime-local
      - traefik.enable=true
      - traefik.http.routers.uptime.rule=Host(`uptime.${DOMAIN}`)
      - traefik.http.routers.uptime.entrypoints=websecure
      - traefik.http.routers.uptime.tls=true
      - traefik.http.services.uptime.loadbalancer.server.port=3001
networks:
  npm:
    external: true
