services:
  db_recipes:
    container_name: db_recipes
    restart: unless-stopped
    image: postgres:16-alpine@sha256:6a388fba16e2a94d6d92bc3c435cdc2e20145add88547615b3d8fa545d703afe
    volumes:
      - ${DOCKER_DATA_DIR}/tandoor/postgresql:/var/lib/postgresql/data
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DB_ENGINE=${DB_ENGINE}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - TZ=${TZ}
      - SOCIAL_PROVIDERS=${SOCIAL_PROVIDERS}
      - SOCIALACCOUNT_PROVIDERS=${SOCIALACCOUNT_PROVIDERS}
    networks:
      - npm
  web_recipes:
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DB_ENGINE=${DB_ENGINE}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - TZ=${TZ}
      - SOCIAL_PROVIDERS=${SOCIAL_PROVIDERS}
      - SOCIALACCOUNT_PROVIDERS=${SOCIALACCOUNT_PROVIDERS}
    volumes:
      - staticfiles:/opt/recipes/staticfiles
      - ${DOCKER_DATA_DIR}/tandoor/mediafiles:/opt/recipes/mediafiles
    depends_on:
      - db_recipes
    container_name: web_recipes
    image: vabene1111/recipes:2.3.6@sha256:5cd01ba0473a48878db3ed9b2c6f2c5db12b68649e169ce9cfa43f052fb0aa95
    restart: unless-stopped
    networks:
      - npm
    labels:
      - traefik.enable=true
      - traefik.docker.network=npm
      - traefik.http.routers.tandoor.rule=Host(`tandoor.${DOMAIN}`)
      - traefik.http.routers.tandoor.entrypoints=websecure
      - traefik.http.routers.tandoor.tls=true
      - traefik.http.services.tandoor.loadbalancer.server.port=80
volumes:
  nginx_config: null
  staticfiles: null
networks:
  npm:
    external: true