services:
  db_recipes:
    container_name: db_recipes
    restart: unless-stopped
    image: postgres:18-alpine@sha256:aa6eb304ddb6dd26df23d05db4e5cb05af8951cda3e0dc57731b771e0ef4ab29
    volumes:
      - ${DOCKER_DATA_DIR}/tandoor/postgresql:/var/lib/postgresql
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DB_ENGINE=${DB_ENGINE}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - TZ=${TZ}
      - SOCIAL_PROVIDERS=${SOCIAL_PROVIDERS}
      - SOCIALACCOUNT_PROVIDERS=${SOCIALACCOUNT_PROVIDERS}
    networks:
      - npm
  web_recipes:
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DB_ENGINE=${DB_ENGINE}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - TZ=${TZ}
      - SOCIAL_PROVIDERS=${SOCIAL_PROVIDERS}
      - SOCIALACCOUNT_PROVIDERS=${SOCIALACCOUNT_PROVIDERS}
    volumes:
      - staticfiles:/opt/recipes/staticfiles
      - ${DOCKER_DATA_DIR}/tandoor/mediafiles:/opt/recipes/mediafiles
    depends_on:
      - db_recipes
    container_name: web_recipes
    image: vabene1111/recipes:2.5.0@sha256:afaa257176f9d64733d27793e557ab680bf381ecef2d207b1a14033a2e4ace0e
    restart: unless-stopped
    networks:
      - npm
    labels:
      - traefik.enable=true
      - traefik.docker.network=npm
      - traefik.http.routers.tandoor.rule=Host(`tandoor.${DOMAIN}`)
      - traefik.http.routers.tandoor.entrypoints=websecure
      - traefik.http.routers.tandoor.tls=true
      - traefik.http.services.tandoor.loadbalancer.server.port=80
volumes:
  nginx_config: null
  staticfiles: null
networks:
  npm:
    external: true
