services:
  db_recipes:
    container_name: db_recipes
    restart: unless-stopped
    image: postgres:18-alpine@sha256:4da1a4828be12604092fa55311276f08f9224a74a62dcb4708bd7439e2a03911
    volumes:
      - ${DOCKER_DATA_DIR}/tandoor/postgresql:/var/lib/postgresql
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DB_ENGINE=${DB_ENGINE}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - TZ=${TZ}
      - SOCIAL_PROVIDERS=${SOCIAL_PROVIDERS}
      - SOCIALACCOUNT_PROVIDERS=${SOCIALACCOUNT_PROVIDERS}
    networks:
      - npm
  web_recipes:
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DB_ENGINE=${DB_ENGINE}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - TZ=${TZ}
      - SOCIAL_PROVIDERS=${SOCIAL_PROVIDERS}
      - SOCIALACCOUNT_PROVIDERS=${SOCIALACCOUNT_PROVIDERS}
    volumes:
      - staticfiles:/opt/recipes/staticfiles
      - ${DOCKER_DATA_DIR}/tandoor/mediafiles:/opt/recipes/mediafiles
    depends_on:
      - db_recipes
    container_name: web_recipes
    image: vabene1111/recipes:2.5.3@sha256:7ce6534c9ab0e471fd0f08add67e871b9173fb580c2f86294c3ead025603a3d7
    restart: unless-stopped
    networks:
      - npm
    labels:
      - traefik.enable=true
      - traefik.docker.network=npm
      - traefik.http.routers.tandoor.rule=Host(`tandoor.${DOMAIN}`)
      - traefik.http.routers.tandoor.entrypoints=websecure
      - traefik.http.routers.tandoor.tls=true
      - traefik.http.services.tandoor.loadbalancer.server.port=80
volumes:
  nginx_config: null
  staticfiles: null
networks:
  npm:
    external: true
