# yaml-language-server: $schema=https://raw.githubusercontent.com/Kometa-Team/Kometa/nightly/json-schema/config-schema.json

############################################
# ######################################## #
# #  _  _____  __  __ _____ _____  _     # #
# # | |/ / _ \|  \/  | ____|_   _|/ \    # #
# # | ' / | | | |\/| |  _|   | | / _ \   # #
# # | . \ |_| | |  | | |___  | |/ ___ \  # #
# # |_|\_\___/|_|  |_|_____| |_/_/   \_\ # #
# #                                      # #
############################################

#==================== compassionate_pike ====================#
# compassionate_pike config created by Quickstart on 2025-09-05 08:58:20
# Connected to server server-michiel version 1.42.1.10060-4e8b05daf
# Running on Linux version 6.12.15-production+truenas
# Plex DB cache setting: 40 MB
# PlexPass: True on Public update channel.
# Scheduled maintenance running between 2:00 and 5:00
# Quickstart version: 0.8.20 | Branch: master | Environment: Docker
###
# Libraries configured with Quickstart: 2 movie, 2 show
# Information on library: Films
# Type: Movie
# Agent: tv.plex.agents.movie
# Scanner: Plex Movie
# Ratings Source: Rotten Tomatoes
# Content Count: 226 movies
# 
# Information on library: Films-ombi
# Type: Movie
# Agent: tv.plex.agents.movie
# Scanner: Plex Movie
# Ratings Source: Rotten Tomatoes
# Content Count: 10 movies
# 
# Information on library: Tv-ombi
# Type: Show
# Agent: tv.plex.agents.series
# Scanner: Plex TV Series
# Ratings Source: N/A
# Content Count: 20 shows / 323 episodes
# 
# Information on library: Tv-series
# Type: Show
# Agent: tv.plex.agents.series
# Scanner: Plex TV Series
# Ratings Source: N/A
# Content Count: 17 shows / 193 episodes
### 
# We highly recommend using Visual Studio Code with indent-rainbow by oderwat extension and YAML by Red Hat extension. Visual Studio Code will also leverage the above link (yaml-language-server) to enhance Kometa yml edits.
###

# This file is auto-generated by Quickstart. Do not edit manually unless you know what you are doing.
#==================== compassionate_pike ====================#


##############################################
#  _     _ _                    _            #
# | |   (_) |__  _ __ __ _ _ __(_) ___  ___  #
# | |   | | '_ \| '__/ _` | '__| |/ _ \/ __| #
# | |___| | |_) | | | (_| | |  | |  __/\__ \ #
# |_____|_|_.__/|_|  \__,_|_|  |_|\___||___/ #
#                                            #
##############################################
libraries:
#############################
#  _____ _ _                #
# |  ___(_) |_ __ ___  ___  #
# | |_  | | | '_ ` _ \/ __| #
# |  _| | | | | | | | \__ \ #
# |_|   |_|_|_| |_| |_|___/ #
#                           #
#############################
  Films:
    template_variables:
      use_separator: false
####################################################
#   ____      _ _           _   _                  #
#  / ___|___ | | | ___  ___| |_(_) ___  _ __  ___  #
# | |   / _ \| | |/ _ \/ __| __| |/ _ \| '_ \/ __| #
# | |__| (_) | | |  __/ (__| |_| | (_) | | | \__ \ #
#  \____\___/|_|_|\___|\__|__|_|\___/|_| |_|___/ #
#                                                  #
####################################################
    collection_files:
    - default: genre
      template_variables:
        collection_section: '060'
        collection_mode: default
        visible_home: false
        visible_library: false
        visible_shared: false
        sort_by: release.desc
    - default: franchise
      template_variables:
        collection_mode: default
        visible_home: false
        visible_library: false
        visible_shared: false
        sort_by: release.desc
############################################
#   ___                 _                  #
#  / _ \__   _____ _ __| | __ _ _   _ ___  #
# | | | \ \ / / _ \ '__| |/ _` | | | / __| #
# | |_| |\ V /  __/ |  | | (_| | |_| \__ \ #
#  \___/  \_/ \___|_|  |_|\__,_|\__, |___/ #
#                               |___/      #
############################################
    overlay_files:
    - default: resolution
    - default: runtimes
    - default: streaming
      template_variables:
        style: color
    - default: studio
      template_variables:
        style: standard
###########################################################
#  _____ _ _                                     _     _  #
# |  ___(_) |_ __ ___  ___        ___  _ __ ___ | |__ (_) #
# | |_  | | | '_ ` _ \/ __|_____ / _ \| '_ ` _ \| '_ \| | #
# |  _| | | | | | | | \__ \_____| (_) | | | | | | |_) | | #
# |_|   |_|_|_| |_| |_|___/      \___/|_| |_| |_|_.__/|_| #
#                                                         #
###########################################################
  Films-ombi:
    template_variables:
      use_separator: false
####################################################
#   ____      _ _           _   _                  #
#  / ___|___ | | | ___  ___| |_(_) ___  _ __  ___  #
# | |   / _ \| | |/ _ \/ __| __| |/ _ \| '_ \/ __| #
# | |__| (_) | | |  __/ (__| |_| | (_) | | | \__ \ #
#  \____\___/|_|_|\___|\__|__|_|\___/|_| |_|___/ #
#                                                  #
####################################################
    collection_files:
    - default: oscars
      template_variables:
        collection_section: '130'
        use_best_picture: false
        radarr_add_missing_best_picture: false
        use_best_director: false
        radarr_add_missing_best_director: false
        collection_mode: default
        visible_home: false
        visible_library: false
        visible_shared: false
        sort_by: release.desc
##############################################
#  _____                            _     _  #
# |_   _|_   __      ___  _ __ ___ | |__ (_) #
#   | | \ \ / /____ / _ \| '_ ` _ \| '_ \| | #
#   | |  \ V /_____| (_) | | | | | | |_) | | #
#   |_|   \_/       \___/|_| |_| |_|_.__/|_| #
#                                            #
##############################################
  Tv-ombi:
    template_variables:
      use_separator: false
####################################################
#   ____      _ _           _   _                  #
#  / ___|___ | | | ___  ___| |_(_) ___  _ __  ___  #
# | |   / _ \| | |/ _ \/ __| __| |/ _ \| '_ \/ __| #
# | |__| (_) | | |  __/ (__| |_| | (_) | | | \__ \ #
#  \____\___/|_|_|\___|\__|__|_|\___/|_| |_|___/ #
#                                                  #
####################################################
    collection_files:
    - default: emmy
      template_variables:
        collection_section: '130'
        use_best: false
        sonarr_add_missing_best: false
        collection_mode: default
        visible_home: false
        visible_library: false
        visible_shared: false
        sort_by: release.desc
    - default: golden
      template_variables:
        collection_section: '130'
        use_best_picture: false
        sonarr_add_missing_best_picture: false
        use_best_director: false
        sonarr_add_missing_best_director: false
        collection_mode: default
        visible_home: false
        visible_library: false
        visible_shared: false
        sort_by: release.desc
    - default: genre
      template_variables:
        collection_section: '060'
        collection_mode: default
        visible_home: false
        visible_library: false
        visible_shared: false
        sort_by: release.desc
############################################
#   ___                 _                  #
#  / _ \__   _____ _ __| | __ _ _   _ ___  #
# | | | \ \ / / _ \ '__| |/ _` | | | / __| #
# | |_| |\ V /  __/ |  | | (_| | |_| \__ \ #
#  \___/  \_/ \___|_|  |_|\__,_|\__, |___/ #
#                               |___/      #
############################################
    overlay_files:
    - default: resolution
    - default: runtimes
    - default: streaming
      template_variables:
        style: color
    - default: studio
      template_variables:
        style: standard

################################################
#  _____                          _            #
# |_   _|_   __     ___  ___ _ __(_) ___  ___  #
#   | | \ \ / /____/ __|/ _ \ '__| |/ _ \/ __| #
#   | |  \ V /_____\__ \  __/ |  | |  __/\__ \ #
#   |_|   \_/      |___/\___|_|  |_|\___||___/ #
#                                              #
################################################
  Tv-series:
    template_variables:
      use_separator: false
####################################################
#   ____      _ _           _   _                  #
#  / ___|___ | | | ___  ___| |_(_) ___  _ __  ___  #
# | |   / _ \| | |/ _ \/ __| __| |/ _ \| '_ \/ __| #
# | |__| (_) | | |  __/ (__| |_| | (_) | | | \__ \ #
#  \____\___/|_|_|\___|\__|__|_|\___/|_| |_|___/ #
#                                                  #
####################################################
    collection_files:
    - default: genre
      template_variables:
        collection_section: '060'
        collection_mode: default
        visible_home: false
        visible_library: false
        visible_shared: false
        sort_by: release.desc

############################################
#   ___                 _                  #
#  / _ \__   _____ _ __| | __ _ _   _ ___  #
# | | | \ \ / / _ \ '__| |/ _` | | | / __| #
# | |_| |\ V /  __/ |  | | (_| | |_| \__ \ #
#  \___/  \_/ \___|_|  |_|\__,_|\__, |___/ #
#                               |___/      #
############################################
    overlay_files:
    - default: resolution
    - default: runtimes
    - default: streaming
      template_variables:
        style: color
    - default: studio
      template_variables:
        style: standard

#########################################
#  ____  _             _ _     _        #
# |  _ \| | __ _ _   _| (_)___| |_ ___  #
# | |_) | |/ _` | | | | | / __| __/ __| #
# |  __/| | (_| | |_| | | \__ \ |_\__ \ #
# |_|   |_|\__,_|\__, |_|_|___/\__|___/ #
#                |___/                  #
#########################################
playlist_files:
- default: playlist
  template_variables:
    libraries:
    - Films
    - Tv-series

##########################################
#  ____       _   _   _                  #
# / ___|  ___| |_| |_(_)_ __   __ _ ___  #
# \___ \ / _ \ __| __| | '_ \ / _` / __| #
#  ___) |  __/ |_| |_| | | | | (_| \__ \ #
# |____/ \___|\__|\__|_|_| |_|\__, |___/ #
#                             |___/      #
##########################################
settings:
  asset_depth: 0
  asset_directory:
  - config/assets
  asset_folders: true
  cache: true
  cache_expiration: 60
  create_asset_folders: false
  custom_repo:
  default_collection_order: release.asc
  delete_below_minimum: true
  delete_not_scheduled: false
  dimensional_asset_rename: false
  download_url_assets: false
  ignore_ids:
  ignore_imdb_ids:
  item_refresh_delay: 0
  minimum_items: 1
  missing_only_released: false
  only_filter_missing: false
  overlay_artwork_filetype: webp_lossy
  overlay_artwork_quality: 90
  playlist_exclude_users:
  playlist_report: false
  playlist_sync_to_users:
  prioritize_assets: false
  run_again_delay: 2
  run_order:
  - operations
  - metadata
  - collections
  - overlays
  save_report: false
  show_asset_not_needed: true
  show_filtered: false
  show_missing: true
  show_missing_assets: true
  show_missing_episode_assets: false
  show_missing_season_assets: false
  show_options: true
  show_unconfigured: true
  show_unfiltered: false
  show_unmanaged: true
  sync_mode: append
  tvdb_language: eng
  verify_ssl: true

####################################################
# __        __   _     _                 _         #
# \ \      / /__| |__ | |__   ___   ___ | | _____  #
#  \ \ /\ / / _ \ '_ \| '_ \ / _ \ / _ \| |/ / __| #
#   \ V  V /  __/ |_) | | | | (_) | (_) |   <\__ \ #
#    \_/\_/ \___|_.__/|_| |_|\___/ \___/|_|\_\___/ #
#                                                  #
####################################################
webhooks:
  changes: gotify
  delete: gotify
  error: gotify
  run_end: gotify
  run_start: gotify

#######################
#  ____  _            #
# |  _ \| | _____  __ #
# | |_) | |/ _ \ \/ / #
# |  __/| |  __/>  <  #
# |_|   |_|\___/_/\_\ #
#                     #
#######################
  version:
plex:
  clean_bundles: true
  db_cache: 40
  empty_trash: false
  optimize: true
  timeout: 60
  token: <<PLEX_TOKEN>>
  url: <<PLEX_URL>>
  verify_ssl: true

##############################
#  _____ __  __ ____  _      #
# |_   _|  \/  |  _ \| |__   #
#   | | | |\/| | | | | '_ \  #
#   | | | |  | | |_| | |_) | #
#   |_| |_|  |_|____/|_.__/  #
#                            #
##############################
tmdb:
  apikey: <<TMDB_API_KEY>>
  cache_expiration: 60
  language: en
  region: NL

#####################################
#  _____           _         _ _ _  #
# |_   _|_ _ _   _| |_ _   _| | (_) #
#   | |/ _` | | | | __| | | | | | | #
#   | | (_| | |_| | |_| |_| | | | | #
#   |_|\__,_|\__,_|\__|\__,_|_|_|_| #
#                                   #
#####################################
tautulli:
  apikey: <<TAUTULLI_API_KEY>>
  url: <<TAUTULLI_URL>>

###################################
#   ____ _ _   _   _       _      #
#  / ___(_) |_| | | |_   _| |__   #
# | |  _| | __| |_| | | | | '_ \  #
# | |_| | | |_|  _  | |_| | |_) | #
#  \____|_|\__|_| |_|\__,_|_.__/  #
#                                 #
###################################
github:
  token: <<GITHUB_TOKEN>>

##############################
#   ___  __  __ ____  _      #
#  / _ \|  \/  |  _ \| |__   #
# | | | | |\/| | | | | '_ \  #
# | |_| | |  | | |_| | |_) | #
#  \___/|_|  |_|____/|_.__/  #
#                            #
##############################
omdb:
  apikey: <<OMDB_API_KEY>>
  cache_expiration: 60

#################################
#   ____       _   _  __        #
#  / ___| ___ | |_(_)/ _|_   _  #
# | |  _ / _ \| __| | |_| | | | #
# | |_| | (_) | |_| |  _| |_| | #
#  \____|\___/ \__|_|_|  \__, | #
#                        |___/  #
#################################
gotify:
  token: <<GOTIFY_TOKEN>>
  url: <<GOTIFY_URL>>

######################################
#  ____           _                  #
# |  _ \ __ _  __| | __ _ _ __ _ __  #
# | |_) / _` |/ _` |/ _` | '__| '__| #
# |  _ < (_| | (_| | (_| | |  | |    #
# |_| \_\__,_|\__,_|\__,_|_|  |_|    #
#                                    #
######################################
radarr:
  add_existing: false
  add_missing: false
  availability: released
  ignore_cache: false
  monitor: true
  monitor_existing: false
  plex_path:
  quality_profile: 2160p Remux
  radarr_path:
  root_folder_path: /media/movies
  search: false
  tag:
  token: <<RADARR_TOKEN>>
  upgrade_existing: false
  url: <<RADARR_URL>>

#######################################
#  ____                               #
# / ___|  ___  _ __   __ _ _ __ _ __  #
# \___ \ / _ \| '_ \ / _` | '__| '__| #
#  ___) | (_) | | | | (_| | |  | |    #
# |____/ \___/|_| |_|\__,_|_|  |_|    #
#                                     #
#######################################
sonarr:
  add_existing: false
  add_missing: false
  cutoff_search: false
  ignore_cache: false
  language_profile: English
  monitor: existing
  monitor_existing: false
  plex_path:
  quality_profile: 2160p Remux
  root_folder_path: /media/tv
  search: false
  season_folder: true
  series_type: standard
  sonarr_path:
  tag:
  token: <<SONARR_TOKEN>>
  upgrade_existing: false
  url: <<SONARR_URL>>

#############################
#  _____          _    _    #
# |_   _| __ __ _| | _| |_  #
#   | || '__/ _` | |/ / __| #
#   | || | | (_| |   <| |_  #
#   |_||_|  \__,_|_|\_\\__| #
#                           #
#############################
trakt:
  authorization:
    access_token: <<TRAKT_ACCESS_TOKEN>>
    created_at: '1754859088'
    expires_in: '86399'
    refresh_token: <<TRAKT_REFRESH_TOKEN>>
    scope: public
    token_type: Bearer
  client_id: <<TRAKT_CLIENT_ID>>
  client_secret: <<TRAKT_CLIENT_SECRET>>
  pin:
  force_refresh: