services:
  wizarr:
    container_name: wizarr
    image: ghcr.io/wizarrrr/wizarr:v2025.11.2@sha256:dbf51675f35cd39db92d0a6522b461eec5e28f65357d804c60daca60ba1f3dd8
    #    ports:
    #      - 5690:5690
    volumes:
      - ${DOCKER_DATA_DIR}/wizarr/database:/data/database
      - ${DOCKER_DATA_DIR}/wizarr/wizard:/data/wizard_steps
    environment:
      - APP_URL=https://wizarr.${DOMAIN} #URL at which you will access and share 
      - DISABLE_BUILTIN_AUTH=false #Set to true ONLY if you are using another auth provider (Authelia, Authentik, etc)
      - TZ=Europe/Amsterdam #Set your timezone here
      - PUID=${PUID} #Set UID
      - PGID=${PGID} #Set GID
    restart: unless-stopped
    networks:
      - npm
    labels:
      - homepage.group=Media Management
      - homepage.name=Wizarr
      - homepage.icon=wizarr.png
      - homepage.href=http://wizarr.${DOMAIN}/
      - homepage.description=Wizarr is an advanced user invitation and
        management system for Plex
      - traefik.enable=true
      - traefik.http.routers.wizarr.rule=Host(`wizarr.${DOMAIN}`)
      - traefik.http.routers.wizarr.entrypoints=websecure
      - traefik.http.routers.wizarr.tls=true
#      - traefik.http.services.wizarr.loadbalancer.server.port=5690

networks:
  npm:
    external: true
