services:
  musicassistant:
    privileged: true
    container_name: musicassistant
    volumes:
      - ${DOCKER_DATA_DIR:?DOCKER_DATA_DIR is not set}/musicassistant/config:/data
    image: ghcr.io/music-assistant/server:2.7.3@sha256:f25a959247df34ed83e756900b775a2ae26fb24b0cc5fa220b70d03e71395ad7
    environment:
      # Provide logging level as environment variable.
      # default=info, possible=(critical, error, warning, info, debug)
      - LOG_LEVEL=info
    cap_add:
      - SYS_ADMIN
      - DAC_READ_SEARCH
    security_opt:
      - apparmor:unconfined
    restart: unless-stopped
    networks:
      my-macvlan-net:
        ipv4_address: ${MUSICASSISTANT_IP:?MUSICASSISTANT_IP is not set}
      npm: null
    labels:
      - homepage.group=Media
      - homepage.name=MusicAssistant
      - homepage.icon=https://www.music-assistant.io/assets/transparent-logo.png
      - homepage.href=http://musicassistant.${DOMAIN:?DOMAIN is not set}/
      - homepage.description=Music library manager for offline & online sources
      - traefik.enable=true
      - traefik.http.routers.musicassistant.rule=Host(`musicassistant.${DOMAIN}`)
      - traefik.docker.network=npm
      - traefik.http.routers.musicassistant.entrypoints=websecure
      - traefik.http.routers.musicassistant.tls=true
      - traefik.http.services.musicassistant.loadbalancer.server.port=8095
networks:
  my-macvlan-net:
    external: true
  npm:
    external: true