services:
  maintainerr:
    image: ghcr.io/maintainerr/maintainerr:3.0.0@sha256:458c44d490af881f783efd3ebb3c1090aebd4cbb0f21779b5599c5689564b71e
    container_name: maintainerr
    user: ${PUID}:${PGID}
    volumes:
      - ${DOCKER_DATA_DIR}/maintainerr/data:/opt/data
    environment:
      - TZ=Europe/Amsterdam
      - PUID=${PUID}
      - PGID=${PGID}
    #      - DEBUG=true # uncomment to enable debug logs
    # ports:
    # - 6246:6246
    restart: unless-stopped
    networks:
      - npm
    labels:
      - homepage.group=Media Management
      - homepage.name=Maintainerr
      - homepage.icon=maintainerr.png
      - homepage.href=http://maintainerr.${DOMAIN}/
      - homepage.description=Maintenance tool for the Plex ecosystem
      - traefik.enable=true
      - traefik.http.routers.maintainerr.rule=Host(`maintainerr.${DOMAIN}`)
      - traefik.http.routers.maintainerr.entrypoints=websecure
      - traefik.http.routers.maintainerr.tls=true
      - traefik.http.services.maintainerr.loadbalancer.server.port=6246
networks:
  npm:
    external: true