services:
  maintainerr:
    image: ghcr.io/maintainerr/maintainerr:2.21.0@sha256:c107c09da8c5dd2f6336c04f41c04c2da1fb8274c357f8680ebf79652d810df4
    container_name: maintainerr
    user: ${PUID}:${PGID}
    volumes:
      - ${DOCKER_DATA_DIR}/maintainerr/data:/opt/data
    environment:
      - TZ=Europe/Amsterdam
      - PUID=${PUID}
      - PGID=${PGID}
    #      - DEBUG=true # uncomment to enable debug logs
    # ports:
    # - 6246:6246
    restart: unless-stopped
    networks:
      - npm
    labels:
      - homepage.group=Media Management
      - homepage.name=Maintainerr
      - homepage.icon=https://raw.githubusercontent.com/jorenn92/Maintainerr/refs/heads/main/ui/public/logo.png
      - homepage.href=http://maintainerr.${DOMAIN}/
      - homepage.description=Maintenance tool for the Plex ecosystem
      - traefik.enable=true
      - traefik.http.routers.maintainerr.rule=Host(`maintainerr.${DOMAIN}`)
      - traefik.http.routers.maintainerr.entrypoints=websecure
      - traefik.http.routers.maintainerr.tls=true
      - traefik.http.services.maintainerr.loadbalancer.server.port=6246
networks:
  npm:
    external: true